### ISSUE TITLE
USB 3.0 not always working

### ISSUE THREAD

**Issue by c0d3z3r0** [tobetter/linux#11]
- USB 3.0 devices often are detected as USB 2.0, only sometimes as 3.0
- USB hub is redetected when new devices are attached
- USB 2.0 works

dmesg:

[    0.263690] usbcore: registered new interface driver usbfs
[    0.263775] usbcore: registered new interface driver hub
[    0.263944] usbcore: registered new device driver usb
[    1.238987] usbcore: registered new interface driver usb-storage
[    1.598565] usbcore: registered new interface driver usbhid
[    1.603651] usbhid: USB HID core driver
[    5.968021] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    5.971402] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    6.021169] exynos-ohci 12120000.usb:: USB Host Controller
[    6.032793] exynos-ohci 12120000.usb:: new USB bus registered, assigned bus number 1
[    6.040368] exynos-ohci 12120000.usb:: irq 130, io mem 0x12120000
[    6.101296] usb usb1: New USB device found, idVendor=1d6b, idProduct=0001
[    6.106601] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    6.113830] usb usb1: Product: USB Host Controller
[    6.118656] usb usb1: Manufacturer: Linux 4.7.2+ ohci_hcd
[    6.123931] usb usb1: SerialNumber: 12120000.usb:
[    6.129286] hub 1-0:1.0: USB hub found
[    6.137242] exynos-ehci 12110000.usb:: EHCI Host Controller
[    6.148942] exynos-ehci 12110000.usb:: new USB bus registered, assigned bus number 2
[    6.149048] exynos-ehci 12110000.usb:: irq 130, io mem 0x12110000
[    6.167021] exynos-ehci 12110000.usb:: USB 2.0 started, EHCI 1.00
[    6.172277] usb usb2: New USB device found, idVendor=1d6b, idProduct=0002
[    6.178462] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    6.178468] usb usb2: Product: EHCI Host Controller
[    6.178474] usb usb2: Manufacturer: Linux 4.7.2+ ehci_hcd
[    6.178480] usb usb2: SerialNumber: 12110000.usb:
[    6.179160] hub 2-0:1.0: USB hub found
[    6.181027] exynos-dwc3 usb3-0:: no suspend clk specified
[    6.183925] usb_phy_generic.0.auto supply vcc not found, using dummy regulator
[    6.184317] usb_phy_generic.1.auto supply vcc not found, using dummy regulator
[    6.185206] exynos-dwc3 usb3-1:: no suspend clk specified
[    6.186802] usb_phy_generic.2.auto supply vcc not found, using dummy regulator
[    6.187207] usb_phy_generic.3.auto supply vcc not found, using dummy regulator
[    6.211272] xhci-hcd xhci-hcd.4.auto: new USB bus registered, assigned bus number 3
[    6.211914] usb usb3: New USB device found, idVendor=1d6b, idProduct=0002
[    6.211921] usb usb3: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    6.211927] usb usb3: Product: xHCI Host Controller
[    6.211932] usb usb3: Manufacturer: Linux 4.7.2+ xhci-hcd
[    6.211936] usb usb3: SerialNumber: xhci-hcd.4.auto
[    6.212537] hub 3-0:1.0: USB hub found
[    6.213275] xhci-hcd xhci-hcd.4.auto: new USB bus registered, assigned bus number 4
[    6.213433] usb usb4: We don't know the algorithms for LPM for this host, disabling LPM.
[    6.213748] usb usb4: New USB device found, idVendor=1d6b, idProduct=0003
[    6.213754] usb usb4: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    6.213759] usb usb4: Product: xHCI Host Controller
[    6.213763] usb usb4: Manufacturer: Linux 4.7.2+ xhci-hcd
[    6.213767] usb usb4: SerialNumber: xhci-hcd.4.auto
[    6.214563] hub 4-0:1.0: USB hub found
[    6.215385] xhci-hcd xhci-hcd.5.auto: new USB bus registered, assigned bus number 5
[    6.215988] usb usb5: New USB device found, idVendor=1d6b, idProduct=0002
[    6.215994] usb usb5: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    6.216001] usb usb5: Product: xHCI Host Controller
[    6.216006] usb usb5: Manufacturer: Linux 4.7.2+ xhci-hcd
[    6.216010] usb usb5: SerialNumber: xhci-hcd.5.auto
[    6.216782] hub 5-0:1.0: USB hub found
[    6.217697] xhci-hcd xhci-hcd.5.auto: new USB bus registered, assigned bus number 6
[    6.217848] usb usb6: We don't know the algorithms for LPM for this host, disabling LPM.
[    6.218075] usb usb6: New USB device found, idVendor=1d6b, idProduct=0003
[    6.218081] usb usb6: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    6.218085] usb usb6: Product: xHCI Host Controller
[    6.218090] usb usb6: Manufacturer: Linux 4.7.2+ xhci-hcd
[    6.218095] usb usb6: SerialNumber: xhci-hcd.5.auto
[    6.218832] hub 6-0:1.0: USB hub found
[    6.536996] usb 3-1: new high-speed USB device number 2 using xhci-hcd
[    6.679531] usb 3-1: New USB device found, idVendor=05e3, idProduct=0610
[    6.684753] usb 3-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    6.684756] usb 3-1: Product: USB2.0 Hub
[    6.684759] usb 3-1: Manufacturer: GenesysLogic
[    6.693652] hub 3-1:1.0: USB hub found
[    6.727024] usb 5-1: new high-speed USB device number 3 using xhci-hcd
[    6.847036] usb 1-1: new full-speed USB device number 2 using exynos-ohci
[    6.877902] usb 5-1: New USB device found, idVendor=0bda, idProduct=8153
[    6.883117] usb 5-1: New USB device strings: Mfr=1, Product=2, SerialNumber=6
[    6.890279] usb 5-1: Product: USB 10/100/1000 LAN
[    6.894900] usb 5-1: Manufacturer: Realtek
[    6.899003] usb 5-1: SerialNumber: 000001000000
[    6.927181] usbcore: registered new interface driver r8152
[    6.936319] usbcore: registered new interface driver cdc_ether
[    7.066066] usb 1-1: New USB device found, idVendor=041e, idProduct=30d3
[    7.083736] usb 5-1: reset high-speed USB device number 3 using xhci-hcd
[    7.083746] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=2
[    7.083752] usb 1-1: SerialNumber: 140113000788
[    7.117251] input: HID 041e:30d3 as /devices/platform/12120000.usb:/usb1/1-1/1-1:1.3/0003:041E:30D3.0001/input/input0
[    7.177171] hid-generic 0003:041E:30D3.0001: input,hidraw0: USB HID v1.00 Device [HID 041e:30d3] on usb-12120000.usb:-1/input3
[    7.346890] usbcore: registered new interface driver snd-usb-audio
[    7.977085] usb 3-1.1: new high-speed USB device number 3 using xhci-hcd
[    8.118821] usb 3-1.1: New USB device found, idVendor=1e68, idProduct=008a
[    8.124230] usb 3-1.1: New USB device strings: Mfr=2, Product=3, SerialNumber=1
[    8.131602] usb 3-1.1: Product: DS picco SSD
[    8.135760] usb 3-1.1: Manufacturer: TrekStor
[    8.140219] usb 3-1.1: SerialNumber: 20151111311B
[    8.163058] usbcore: registered new interface driver uas
[   14.177117] usb 4-1: new SuperSpeed USB device number 2 using xhci-hcd
[   14.199768] usb 4-1: New USB device found, idVendor=05e3, idProduct=0616
[   14.204984] usb 4-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[   14.212147] usb 4-1: Product: USB3.0 Hub
[   14.215988] usb 4-1: Manufacturer: GenesysLogic
[   14.230097] hub 4-1:1.0: USB hub found
[  260.934897] usb 3-1.1: USB disconnect, device number 3
[  270.516023] usb 4-1: USB disconnect, device number 2
[  270.629382] usb 3-1: reset high-speed USB device number 2 using xhci-hcd
[  271.146121] usb 4-1: new SuperSpeed USB device number 3 using xhci-hcd
[  271.168736] usb 4-1: New USB device found, idVendor=05e3, idProduct=0616
[  271.173999] usb 4-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[  271.181189] usb 4-1: Product: USB3.0 Hub
[  271.185017] usb 4-1: Manufacturer: GenesysLogic
[  271.206155] hub 4-1:1.0: USB hub found
[  271.486057] usb 4-1.1: new SuperSpeed USB device number 4 using xhci-hcd
[  271.507123] usb 4-1.1: New USB device found, idVendor=1e68, idProduct=008a
[  271.512556] usb 4-1.1: New USB device strings: Mfr=2, Product=3, SerialNumber=1
[  271.519914] usb 4-1.1: Product: DS picco SSD
[  271.524095] usb 4-1.1: Manufacturer: TrekStor
[  271.528459] usb 4-1.1: SerialNumber: 20151111311B
[  271.534158] usb 4-1.1: USB controller xhci-hcd.4.auto does not support streams, which are required by the UAS driver.
[  271.543756] usb 4-1.1: Please try an other USB controller if you wish to use UAS.
[  271.551182] usb-storage 4-1.1:1.0: USB Mass Storage device detected
[  271.557924] scsi host0: usb-storage 4-1.1:1.0
[  311.669882] usb 4-1.1: USB disconnect, device number 4
[  323.737746] usb 3-1-port1: connect-debounce failed
[  323.742604] usb 3-1: USB disconnect, device number 2
[  323.856536] usb 4-1: USB disconnect, device number 3
[  324.076455] usb 3-1: new high-speed USB device number 5 using xhci-hcd
[  324.218979] usb 3-1: New USB device found, idVendor=05e3, idProduct=0610
[  324.224241] usb 3-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[  324.231400] usb 3-1: Product: USB2.0 Hub
[  324.235299] usb 3-1: Manufacturer: GenesysLogic
[  324.261856] hub 3-1:1.0: USB hub found
[  325.546471] usb 3-1.1: new high-speed USB device number 6 using xhci-hcd
[  325.688272] usb 3-1.1: New USB device found, idVendor=1e68, idProduct=008a
[  325.693727] usb 3-1.1: New USB device strings: Mfr=2, Product=3, SerialNumber=1
[  325.701092] usb 3-1.1: Product: DS picco SSD
[  325.705239] usb 3-1.1: Manufacturer: TrekStor
[  325.709644] usb 3-1.1: SerialNumber: 20151111311B
[  326.446648] usb 4-1: new SuperSpeed USB device number 5 using xhci-hcd
[  326.469403] usb 4-1: New USB device found, idVendor=05e3, idProduct=0616
[  326.474684] usb 4-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[  326.481815] usb 4-1: Product: USB3.0 Hub
[  326.485668] usb 4-1: Manufacturer: GenesysLogic
[  326.502189] hub 4-1:1.0: USB hub found

**Comment by c0d3z3r0** [comment]
On the 4.8 branch USB 3.0 does not work at all:

[  114.162408] usb 1-1: USB disconnect, device number 2
[  114.162408] usb 1-1: USB disconnect, device number 2
[  117.000031] usb usb1-port1: connect-debounce failed
[  117.000031] usb usb1-port1: connect-debounce failed

**Comment by jobenvil** [comment]
@c0d3z3r0 not really, indeed it works, but maybe not with your USB3 Adapter. I realized this testing 4.8-rc5. With JMICRON567 it doesn't work anymore but with ASMEDIA ([see my last post here](https://github.com/tobetter/linux/issues/5)) it works, but without UAS.

**Comment by ardje** [comment]
I actually have very good and very bad experiences with USB3.
The bad:
Using an epiphan AV.IO 4k, an USB3 UVC class video grabber and vlc I can repeatedly disconnect the internal USB3 hub, which needs a powercycle to recover even if the epiphan is disconnected.
With 3.10 I can usually send a usbreset to the USB2 counterpart of the internal USB3 hub, and reset the USB3 hub like that, after which it re-appears.
So there are is one obvious problem: the kernel is unable to send a proper reset to the USB3 hub upon boot. Come to think of it: maybe the problem is, that it sends it to the USB2 hub too, and hence the sense of the USB3 hub fails. Nah, that should have been a problem everytime.
The good:
(only) After a _power cycle_, the cloudshell feels rock sold, and is blazingly fast with a WD-RED 2.5" disk.

**Comment by jobenvil** [comment]
Maybe [these threads](https://www.google.de/search?q=hardkernel+forum%3A+xu3+xu4+reset+usb3+site%3Aforum.odroid.com&oq=hardkernel+forum%3A+xu3+xu4+reset+usb3+site%3Aforum.odroid.com&aqs=chrome..69i57.567j0j7&sourceid=chrome&ie=UTF-8) could interest you

**Comment by c0d3z3r0** [comment]
Closing this since I sold my Odroid. I'm fed up with ARM...
