### ISSUE TITLE
odroid-6.1.y branch is missing rk3568-gpiomem.c

### ISSUE THREAD

**Issue by jimmyhon** [tobetter/linux#46]
The object file is referenced by the Makefile, but the C file was not added in the commit.

https://github.com/tobetter/linux/commit/3a163dc2f239e1dbfed4cdb9ee515ef542684d1f#diff-3ecbae0b5d2a1c7684951cd0b643259df579598f3406d91c30110d0b3bfde6f0R50

```
make[3]: *** No rule to make target 'drivers/char/rk3568-gpiomem.o', needed by 'drivers/char/built-in.a'.  Stop.
make[2]: *** [scripts/Makefile.build:500: drivers/char] Error 2
make[1]: *** [scripts/Makefile.build:500: drivers] Error 2
make: *** [Makefile:2012: .] Error 2
```

**Comment by how2flow** [comment]
The source file was missed when merging.. It's been modified.
remote update and try again.

**Comment by jimmyhon** [comment]
Thanks for the quick update. It works.
