### ISSUE TITLE
UHS-I sdxc cards not detected as uhs

### ISSUE THREAD

**Issue by c0d3z3r0** [tobetter/linux#9]
My Transcend UHS-I SDXC card is not detected as UHS-I

dmesg Odroid-XU4:
[    1.869449] mmc1: new high speed SDXC card at address 59b4

dmesg laptop:
[21388.964579] mmc0: new ultra high speed SDR104 SDHC card at address 59b4

**Comment by tobetter** [comment]
What's the kernel version?

**Comment by c0d3z3r0** [comment]
Oh, I'm sorry...   4.6 and 4.7

**Comment by jobenvil** [comment]
having the same with 4.8.0-rc-3.

**Comment by tobetter** [comment]
Could you let me know exact model number of your card? I don't have Trescend one.

**Comment by c0d3z3r0** [comment]
Yep, it's a Transcend TS32GUSDU1. I don't have anything than Transcend here so I can't tell if it's a vendor specific problem. @jobenvil is your's a Transcend card, too?

**Comment by jobenvil** [comment]
@c0d3z3r0 I have a SanDisk Ultra 8GB Micro SDHC-I Class 10 (this is not an XC, but an HC, thus should be UHS-I, or I'm wrong?). On the back is wroten 6111DKCKT0JN

```
root@hiperborea:~# dmesg| grep SD
[    3.774760] sdhci-pltfm: SDHCI platform and OF driver helper
[    3.876054] mmc1: new high speed SDHC card at address aaaa

```

**Comment by c0d3z3r0** [comment]
Yeah, SanDisk Ultra SDHC is UHS-I, too

**Comment by c0d3z3r0** [comment]
@jobenvil did you apply [1] and [2] onto 4.8.0-rc-3?

[1] https://github.com/tobetter/linux/commit/206dbdea8b7a9bc672640c164072383424461393
[2] https://github.com/tobetter/linux/commit/12219a31c0aa8b4d2980c088040330d8dd8f00a9

**Comment by jobenvil** [comment]
@c0d3z3r0 No, until you point me out, but still doesn't get recogniced. @tobetter are these patches providing some type of speed increment or only differs in the name denomination?

**Comment by c0d3z3r0** [comment]
@jobenvil those patches aren't in mainline. could you try 4.8.0-rc3 with them applied so that we can see if your card is working?

**Comment by jobenvil** [comment]
@c0d3z3r0 I applied these both yesterday on 4.8.0-rc3 with [cd8a88d](https://github.com/torvalds/linux/commit/cd8a88d523598df5baa8039611680afac35f5487), this [0e0d124](https://github.com/tobetter/linux/commit/0e0d124ea9381e9e77996be31fa424d2b86c736b) and this [d6a899d](https://github.com/torvalds/linux/commit/d6a899de186f833e5980aaf9463e0fa519e227b1) as well. It doesn't worked `eth0`and therefore it only could be accessed by serial. I checked `dmesg` and still high speed.

**Comment by c0d3z3r0** [comment]
Ok, that means it is not a card specific issue

**Comment by jobenvil** [comment]
I'm not sure, thus in my banana pro with kernel 4.6.3 is the same as the XU4 and I don't have more UHS-I cards to test with. Maybe someone listening here wants to post if the UHS-I patches works in his XU4?

**Comment by c0d3z3r0** [comment]
The patches are XU3/4 specific - you cannot compare the behaviour of XU3/4 with that of banana pi

**Comment by c0d3z3r0** [comment]
Aha... the patches do work but only on cold boot... I'll try to fix this and prepare a patch next week or so

**Comment by jobenvil** [comment]
> The patches are XU3/4 specific - you cannot compare the behaviour of XU3/4 with that of banana pi

I know, but I saw earlier somewhere on my other ARMs "ultra high speed", I don't remember in which and with which kernel. 

I tested your `xu4-update` offline and worked fine. Here is the [dmesg log](http://pastebin.com/eKEkaPGj). 

The SD-card becomes recogniced like UHS-I:

```
[    1.728730] mmc_host mmc1: Bus speed (slot 0) = 50000000Hz (slot req 50000000Hz, actual 50000000HZ div = 0)
[    1.729602] mmc1: new ultra high speed DDR50 SDHC card at address aaaa
[    1.730145] mmcblk1: mmc1:aaaa SL08G 7.40 GiB
[    1.731142]  mmcblk1: p1 p2
```

Thanks for your efforts and sharing XU4 tools. This is a nice improvement.

**Comment by c0d3z3r0** [comment]
Could you check dmesg after a reboot, please

**Comment by jobenvil** [comment]
[here](http://pastebin.com/ruRNJ7Rd) after `shutdown -r now`
confirmed your theory:
`[    1.872958] mmc1: new high speed SDHC card at address aaaa`

**Comment by c0d3z3r0** [comment]
Thank you!
That's what I said yesterday. The patches only work on cold boot, not after a reboot.

**Comment by jobenvil** [comment]
testing SD-Card with:
`iozone -e -I -a -s 100M -r 4k -r 16k -r 32k -r 512k -r 1024k -r 16384k -i 0 -i 1 -i 2`
did show same results on both cases: "ultra high speed vs. high speed", but the UHS-I improvement could be present in other field like, power energy.

**Comment by c0d3z3r0** [comment]
@jobenvil my SD card has ~16 MB/s in HS vs. ~70 MB/s in UHS-I mode

**Comment by c0d3z3r0** [comment]
Looks like the card has to be reset shortly bevore reboot... I added a mdelay(10000) and reattached the sd card in those 10 seconds... after reboot it's detected as UHS

**Comment by jobenvil** [comment]
compiled last tobetter 4.8-rc5. When it succesfully boots with USB3 + UHS-I, I tested the uSD-Card and then, the SSD. The UHS-I patch performs brutally good, awesome because the random read and write values!, but somehow uas could not be recogniced. By other side the ioft/linux repository, with same kernel 4.8-rc5 + uas performs really good, but misses this patch. Comparing both branches, It looks like that these patches `([1] 206dbde and [2] 12219a3)` can not be merged on the top. [See yourself the results.](http://pastebin.com/FznzpG8W)
Maybe consider to read this [[1](http://forum.odroid.com/viewtopic.php?f=93&t=21351)] and this [[2](http://forum.odroid.com/viewtopic.php?f=95&t=23163&p=159703#p159703)].

**Comment by c0d3z3r0** [comment]
@jobenvil I can apply the patches without any problem.
USB 3.0 has nothing to do with UHS

**Comment by jobenvil** [comment]
@c0d3z3r0 ptaches on tobetter repository are oke, but try to apply UHS-I patch on top of the ioft repository master branch

**Comment by c0d3z3r0** [comment]
ah, I'm sorry - I misunderstood that

**Comment by c0d3z3r0** [comment]
Closing this since I sold my Odroid. I'm fed up with ARM...
